name: Auto Assign Issue

on:
  issue_comment:
    types: [created]

jobs:
  assign_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check /assign command
        if: contains(github.event.comment.body, '/assign')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignee = context.payload.comment.user.login;
            await github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [assignee],
            });
